name: "Windows-specific Tests"
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        go: [1.19]

    env:
      GO111MODULE: "on"

    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: src/github.com/nats-io/nats-server

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go}}

      - name: Run tests
        run: |
          go test -vet=off ./... -run=TestWindows
